CREATE TABLE IF NOT EXISTS users(

 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(255) NOT NULL,
 password VARCHAR(255) NOT NULL,
 nickname VARCHAR(255),
 profile_image_key VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS board(
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 content text,
 title VARCHAR(255),
 user_id BIGINT,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

 FOREIGN KEY (user_id)
 REFERENCES users(id)
);


CREATE TABLE IF NOT EXISTS comment (

 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 content text,
 board_id BIGINT,
 user_id BIGINT,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP ,
 updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

 FOREIGN KEY (user_id)
 REFERENCES users(id),

 FOREIGN KEY (board_id)
 REFERENCES board(id)
);
